#ifndef GBFW_PRIVATE_CLOCKS_H
#define GBFW_PRIVATE_CLOCKS_H

#define GBFW_CLOCKS_HSI   16000000
#define GBFW_CLOCKS_PLL_N 85
#define GBFW_CLOCKS_PLL_M 3
#define GBFW_CLOCKS_PLL_R 0

#define GBFW_CLOCKS_DEFAULT_FREQ (GBFW_CLOCKS_HSI * GBFW_CLOCKS_PLL_N) / ((GBFW_CLOCKS_PLL_M + 1) << (GBFW_CLOCKS_PLL_R + 1))

#if GBFW_CLOCKS_DEFAULT_FREQ > 150000000
#define GBFW_CLOCKS_R1_MODE 0
#define GBFW_FLASH_WS ((GBFW_CLOCKS_DEFAULT_FREQ / 34000000) - 1)
#else
#define GBFW_CLOCKS_R1_MODE 1
#define GBFW_FLASH_WS ((GBFW_CLOCKS_DEFAULT_FREQ / 30000000) - 1)
#endif

void gbfw_clocks_default(void);

#endif
